networks:
  default:
    name: external-network
    external: true


services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test_api
      - MYSQL_DATABASE=test_api
    volumes:
      - './mysql-data:/var/lib/mysql'
    ports:
      - '3306:3306'

  api:
    restart: always
    container_name: api
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - ${PORT}:${PORT}