networks:
  default:
    name: external-network
    external: true


services:
  redis:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - '6379:6379'

  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test_api
      - MYSQL_DATABASE=test_api
    volumes:
      - './mysql-data:/var/lib/mysql'
    ports:
      - '3306:3306'